# controller_manager:
#   ros__parameters:
#     update_rate: 50  # Hz
#     use_sim_time: true
    
#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster
      
#     effort_controllers:
#       type: effort_controllers/JointGroupEffortController

# # Joint State Broadcaster Configuration
# joint_state_broadcaster:
#   ros__parameters:
#     joints:
#       - front_right_hip_joint
#       - front_right_knee_joint
#       - front_left_hip_joint
#       - front_left_knee_joint
#       - rear_right_hip_joint
#       - rear_right_knee_joint
#       - rear_left_hip_joint
#       - rear_left_knee_joint
#     publish_rate: 50.0

# # Effort Controllers Configuration
# effort_controllers:
#   ros__parameters:
#     joints:
#       - front_right_hip_joint
#       - front_right_knee_joint
#       - front_left_hip_joint
#       - front_left_knee_joint
#       - rear_right_hip_joint
#       - rear_right_knee_joint
#       - rear_left_hip_joint
#       - rear_left_knee_joint
#     interface_name: effort



controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    use_sim_time: true
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    effort_controllers:
      type: effort_controllers/JointGroupEffortController

# Joint State Broadcaster Configuration
joint_state_broadcaster:
  ros__parameters:
    joints:
      - front_right_hip_joint
      - front_right_knee_joint
      - front_left_hip_joint
      - front_left_knee_joint
      - rear_right_hip_joint
      - rear_right_knee_joint
      - rear_left_hip_joint
      - rear_left_knee_joint
    publish_rate: 50.0

# Effort Controllers Configuration
effort_controllers:
  ros__parameters:
    joints:
      - front_right_hip_joint
      - front_right_knee_joint
      - front_left_hip_joint
      - front_left_knee_joint
      - rear_right_hip_joint
      - rear_right_knee_joint
      - rear_left_hip_joint
      - rear_left_knee_joint
    interface_name: effort
    gains:
      front_right_hip_joint: {p: 50.0, i: 0.01, d: 5.0}
      front_right_knee_joint: {p: 50.0, i: 0.01, d: 5.0}
      front_left_hip_joint: {p: 50.0, i: 0.01, d: 5.0}
      front_left_knee_joint: {p: 50.0, i: 0.01, d: 5.0}
      rear_right_hip_joint: {p: 50.0, i: 0.01, d: 5.0}
      rear_right_knee_joint: {p: 50.0, i: 0.01, d: 5.0}
      rear_left_hip_joint: {p: 50.0, i: 0.01, d: 5.0}
      rear_left_knee_joint: {p: 50.0, i: 0.01, d: 5.0}