<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Leg Parameters -->
  <xacro:property name="leg_offset_x" value="0.15" />
  <xacro:property name="leg_offset_y" value="0.13" />
  <xacro:property name="upper_leg_length" value="0.15" />
  <xacro:property name="upper_leg_radius" value="0.02" />
  <xacro:property name="upper_leg_mass" value="0.2" />
  <xacro:property name="lower_leg_length" value="0.15" />
  <xacro:property name="lower_leg_radius" value="0.01" />
  <xacro:property name="lower_leg_mass" value="0.1" />
  <xacro:property name="foot_radius" value="0.02" />
  <xacro:property name="foot_mass" value="0.05" />

  <!-- Leg macro -->
  <xacro:macro name="leg" params="prefix reflect_x reflect_y">
    <!-- Hip joint -->
    <joint name="${prefix}_hip_joint" type="revolute">
      <parent link="base_link"/>
      <child link="${prefix}_upper_leg"/>
      <origin xyz="${reflect_x * leg_offset_x} ${reflect_y * leg_offset_y} 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-1.57" upper="1.57" effort="10" velocity="3"/>
    </joint>

    <!-- Upper leg link -->
    <link name="${prefix}_upper_leg">
      <visual>
        <origin xyz="0 0 -${upper_leg_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${upper_leg_radius}" length="${upper_leg_length}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 -${upper_leg_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${upper_leg_radius}" length="${upper_leg_length}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 -${upper_leg_length/2}" rpy="0 0 0"/>
        <mass value="${upper_leg_mass}"/>
        <xacro:cylinder_inertia m="${upper_leg_mass}" r="${upper_leg_radius}" h="${upper_leg_length}"/>
      </inertial>
    </link>

    <!-- Knee joint -->
    <joint name="${prefix}_knee_joint" type="revolute">
      <parent link="${prefix}_upper_leg"/>
      <child link="${prefix}_lower_leg"/>
      <origin xyz="0 0 -${upper_leg_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.57" upper="1.57" effort="10" velocity="3"/>
    </joint>

    <!-- Lower leg link -->
    <link name="${prefix}_lower_leg">
      <visual>
        <origin xyz="0 0 -${lower_leg_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${lower_leg_radius}" length="${lower_leg_length}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <origin xyz="0 0 -${lower_leg_length/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="${lower_leg_radius}" length="${lower_leg_length}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 -${lower_leg_length/2}" rpy="0 0 0"/>
        <mass value="${lower_leg_mass}"/>
        <xacro:cylinder_inertia m="${lower_leg_mass}" r="${lower_leg_radius}" h="${lower_leg_length}"/>
      </inertial>
    </link>

    <!-- Foot joint -->
    <joint name="${prefix}_foot_joint" type="fixed">
      <parent link="${prefix}_lower_leg"/>
      <child link="${prefix}_foot"/>
      <origin xyz="0 0 -${lower_leg_length}" rpy="0 0 0"/>
    </joint>

    <!-- Foot link -->
    <link name="${prefix}_foot">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${foot_radius}"/>
        </geometry>
        <material name="orange"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="${foot_radius}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${foot_mass}"/>
        <inertia 
          ixx="${2.0*foot_mass*foot_radius*foot_radius/5.0}" ixy="0.0" ixz="0.0"
          iyy="${2.0*foot_mass*foot_radius*foot_radius/5.0}" iyz="0.0" 
          izz="${2.0*foot_mass*foot_radius*foot_radius/5.0}"
        />
      </inertial>
    </link>
  </xacro:macro>

</robot>